name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Update this to a compatible Node.js version

      - name: Install project dependencies
        run: npm ci

      - name: Deploy to Firebase Hosting
        run: npx firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}
